const products = [
  {
    title: "iPhone X",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    brand: "Apple",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/2/1.jpg",
      "https://i.dummyjson.com/data/products/2/2.jpg",
      "https://i.dummyjson.com/data/products/2/3.jpg",
      "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    ],
    stock: 34,
    review: [],
  },
  {
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    brand: "Samsung",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    AdditionalImages: ["https://i.dummyjson.com/data/products/3/1.jpg"],
    stock: 36,
    review: [],
  },
  {
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    brand: "OPPO",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/4/1.jpg",
      "https://i.dummyjson.com/data/products/4/2.jpg",
      "https://i.dummyjson.com/data/products/4/3.jpg",
      "https://i.dummyjson.com/data/products/4/4.jpg",
      "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    ],
    stock: 123,
    review: [],
  },
  {
    title: "Huawei P30",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    brand: "Huawei",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/5/1.jpg",
      "https://i.dummyjson.com/data/products/5/2.jpg",
      "https://i.dummyjson.com/data/products/5/3.jpg",
    ],
    stock: 32,
    review: [],
  },
  {
    title: "Sneaker shoes",
    description:
      "Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women",
    price: 120,
    discountPercentage: 10.37,
    rating: 4.19,
    brand: "Synthetic Leather",
    category: "womens-shoes",
    image: "https://i.dummyjson.com/data/products/47/thumbnail.jpeg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/47/1.jpg",
      "https://i.dummyjson.com/data/products/47/2.jpg",
      "https://i.dummyjson.com/data/products/47/3.jpg",
      "https://i.dummyjson.com/data/products/47/thumbnail.jpeg",
    ],
    stock: 50,
    review: [],
  },
  {
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    brand: "Apple",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/1/1.jpg",
      "https://i.dummyjson.com/data/products/1/2.jpg",
      "https://i.dummyjson.com/data/products/1/3.jpg",
      "https://i.dummyjson.com/data/products/1/4.jpg",
      "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    ],
    stock: 94,
    review: [],
  },
  {
    title: "Chappals & Shoe Ladies Metallic",
    description:
      "Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals",
    price: 23,
    discountPercentage: 2.62,
    rating: 4.72,
    brand: "Maasai Sandals",
    category: "womens-shoes",
    image: "https://i.dummyjson.com/data/products/49/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/49/1.jpg",
      "https://i.dummyjson.com/data/products/49/2.jpg",
      "https://i.dummyjson.com/data/products/49/3.webp",
      "https://i.dummyjson.com/data/products/49/thumbnail.jpg",
    ],
    stock: 107,
    review: [],
  },
  {
    title: "Women Shoes",
    description:
      "2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes",
    price: 36,
    discountPercentage: 16.87,
    rating: 4.33,
    brand: "Arrivals Genuine",
    category: "womens-shoes",
    image: "https://i.dummyjson.com/data/products/50/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/50/1.jpeg",
      "https://i.dummyjson.com/data/products/50/2.jpg",
      "https://i.dummyjson.com/data/products/50/3.jpg",
    ],
    stock: 46,
    review: [],
  },
  {
    title: "Women Shoulder Bags",
    description:
      "LouisWill Women Shoulder Bags Long Clutches Cross Body Bags Phone Bags PU Leather Hand Bags Large Capacity Card Holders Zipper Coin Purses Fashion Crossbody Bags for Girls Ladies",
    price: 46,
    discountPercentage: 14.65,
    rating: 4.71,
    brand: "LouisWill",
    category: "womens-bags",
    image: "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/71/1.jpg",
      "https://i.dummyjson.com/data/products/71/2.jpg",
      "https://i.dummyjson.com/data/products/71/3.webp",
      "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
    ],
    stock: 17,
    review: [],
  },
  {
    title: "Handbag For Girls",
    description:
      "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
    price: 23,
    discountPercentage: 17.5,
    rating: 4.91,
    brand: "LouisWill",
    category: "womens-bags",
    image: "https://i.dummyjson.com/data/products/72/thumbnail.webp",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/72/1.jpg",
      "https://i.dummyjson.com/data/products/72/2.png",
      "https://i.dummyjson.com/data/products/72/3.webp",
      "https://i.dummyjson.com/data/products/72/4.jpg",
      "https://i.dummyjson.com/data/products/72/thumbnail.webp",
    ],
    stock: 27,
    review: [],
  },
  {
    title: "Fancy hand clutch",
    description:
      "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
    price: 44,
    discountPercentage: 10.39,
    rating: 4.18,
    brand: "Bracelet",
    category: "womens-bags",
    image: "https://i.dummyjson.com/data/products/73/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/73/1.jpg",
      "https://i.dummyjson.com/data/products/73/2.webp",
      "https://i.dummyjson.com/data/products/73/3.jpg",
      "https://i.dummyjson.com/data/products/73/thumbnail.jpg",
    ],
    stock: 101,
    review: [],
  },
  {
    title: "Leather Hand Bag",
    description:
      "It features an attractive design that makes it a must have accessory in your collection. We sell different kind of bags for boys, kids, women, girls and also for unisex.",
    price: 57,
    discountPercentage: 11.19,
    rating: 4.01,
    brand: "Copenhagen Luxe",
    category: "womens-bags",
    image: "https://i.dummyjson.com/data/products/74/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/74/1.jpg",
      "https://i.dummyjson.com/data/products/74/2.jpg",
      "https://i.dummyjson.com/data/products/74/3.jpg",
      "https://i.dummyjson.com/data/products/74/4.jpg",
      "https://i.dummyjson.com/data/products/74/thumbnail.jpg",
    ],
    stock: 43,
    review: [],
  },
  {
    title: "Seven Pocket Women Bag",
    description:
      "Seven Pocket Women Bag Handbags Lady Shoulder Crossbody Bag Female Purse Seven Pocket Bag",
    price: 68,
    discountPercentage: 14.87,
    rating: 4.93,
    brand: "Steal Frame",
    category: "womens-bags",
    image: "https://i.dummyjson.com/data/products/75/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/75/1.jpg",
      "https://i.dummyjson.com/data/products/75/2.jpg",
      "https://i.dummyjson.com/data/products/75/3.jpg",
      "https://i.dummyjson.com/data/products/75/thumbnail.jpg",
    ],
    stock: 13,
    review: [],
  },
  {
    title: "Steel Analog Couple Watches",
    description: "Elegant design, Stylish ,Unique & Trendy,Comfortable wear",
    price: 35,
    discountPercentage: 3.23,
    rating: 4.79,
    brand: "Eastern Watches",
    category: "womens-watches",
    image: "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/66/1.jpg",
      "https://i.dummyjson.com/data/products/66/2.jpg",
      "https://i.dummyjson.com/data/products/66/3.jpg",
      "https://i.dummyjson.com/data/products/66/4.JPG",
      "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
    ],
    stock: 24,
    review: [],
  },
  {
    title: "Fashion Magnetic Wrist Watch",
    description:
      "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
    price: 60,
    discountPercentage: 16.69,
    rating: 4.03,
    brand: "Eastern Watches",
    category: "womens-watches",
    image: "https://i.dummyjson.com/data/products/67/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/67/1.jpg",
      "https://i.dummyjson.com/data/products/67/2.jpg",
      "https://i.dummyjson.com/data/products/67/3.jpg",
      "https://i.dummyjson.com/data/products/67/4.jpg",
      "https://i.dummyjson.com/data/products/67/thumbnail.jpg",
    ],
    stock: 46,
    review: [],
  },
  {
    title: "Stylish Luxury Digital Watch",
    description:
      "Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls",
    price: 57,
    discountPercentage: 9.03,
    rating: 4.55,
    brand: "Luxury Digital",
    category: "womens-watches",
    image: "https://i.dummyjson.com/data/products/68/thumbnail.webp",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/68/1.jpg",
      "https://i.dummyjson.com/data/products/68/2.jpg",
    ],
    stock: 77,
    review: [],
  },
  {
    title: "Golden Watch Pearls Bracelet Watch",
    description:
      "Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women",
    price: 47,
    discountPercentage: 17.55,
    rating: 4.77,
    brand: "Watch Pearls",
    category: "womens-watches",
    image: "https://i.dummyjson.com/data/products/69/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/69/1.jpg",
      "https://i.dummyjson.com/data/products/69/2.jpg",
      "https://i.dummyjson.com/data/products/69/3.webp",
      "https://i.dummyjson.com/data/products/69/4.jpg",
      "https://i.dummyjson.com/data/products/69/thumbnail.jpg",
    ],
    stock: 89,
    review: [],
  },
  {
    title: "Stainless Steel Women",
    description:
      "Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies",
    price: 35,
    discountPercentage: 8.98,
    rating: 3.4,
    brand: "Bracelet",
    category: "womens-watches",
    image: "https://i.dummyjson.com/data/products/70/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/70/1.jpg",
      "https://i.dummyjson.com/data/products/70/2.jpg",
      "https://i.dummyjson.com/data/products/70/thumbnail.jpg",
    ],
    stock: 111,
    review: [],
  },
  {
    title: "Sneakers Joggers Shoes",
    description:
      "Gender: Men , Colors: Same as DisplayedCondition: 100% Brand New",
    price: 40,
    discountPercentage: 12.57,
    rating: 4.38,
    brand: "Sneakers",
    category: "mens-shoes",
    image: "https://i.dummyjson.com/data/products/56/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/56/1.jpg",
      "https://i.dummyjson.com/data/products/56/2.jpg",
      "https://i.dummyjson.com/data/products/56/3.jpg",
      "https://i.dummyjson.com/data/products/56/4.jpg",
      "https://i.dummyjson.com/data/products/56/5.jpg",
      "https://i.dummyjson.com/data/products/56/thumbnail.jpg",
    ],
    stock: 6,
    review: [],
  },
  {
    title: "Loafers for men",
    description:
      "Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccassion - Pure Nylon (Rubber) Expot Quality.",
    price: 47,
    discountPercentage: 10.91,
    rating: 4.91,
    brand: "Rubber",
    category: "mens-shoes",
    image: "https://i.dummyjson.com/data/products/57/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/57/1.jpg",
      "https://i.dummyjson.com/data/products/57/2.jpg",
      "https://i.dummyjson.com/data/products/57/3.jpg",
      "https://i.dummyjson.com/data/products/57/4.jpg",
      "https://i.dummyjson.com/data/products/57/thumbnail.jpg",
    ],
    stock: 20,
    review: [],
  },
  {
    title: "women's shoes",
    description:
      "Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber",
    price: 40,
    discountPercentage: 16.96,
    rating: 4.14,
    brand: "IELGY fashion",
    category: "womens-shoes",
    image: "https://i.dummyjson.com/data/products/46/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/46/1.webp",
      "https://i.dummyjson.com/data/products/46/2.jpg",
      "https://i.dummyjson.com/data/products/46/3.jpg",
      "https://i.dummyjson.com/data/products/46/4.jpg",
      "https://i.dummyjson.com/data/products/46/thumbnail.jpg",
    ],
    stock: 72,
    review: [],
  },
  {
    title: "Spring and summershoes",
    description:
      "Comfortable stretch cloth, lightweight body; ,rubber sole, anti-skid wear;",
    price: 20,
    discountPercentage: 8.71,
    rating: 4.33,
    brand: "Sneakers",
    category: "mens-shoes",
    image: "https://i.dummyjson.com/data/products/59/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/59/1.jpg",
      "https://i.dummyjson.com/data/products/59/2.jpg",
      "https://i.dummyjson.com/data/products/59/3.jpg",
      "https://i.dummyjson.com/data/products/59/4.jpg",
      "https://i.dummyjson.com/data/products/59/thumbnail.jpg",
    ],
    stock: 137,
    review: [],
  },
  {
    title: "Stylish Casual Jeans Shoes",
    description:
      "High Quality ,Stylish design ,Comfortable wear ,FAshion ,Durable",
    price: 58,
    discountPercentage: 7.55,
    rating: 4.55,
    brand: "Sneakers",
    category: "mens-shoes",
    image: "https://i.dummyjson.com/data/products/60/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/60/1.jpg",
      "https://i.dummyjson.com/data/products/60/2.jpg",
      "https://i.dummyjson.com/data/products/60/3.jpg",
      "https://i.dummyjson.com/data/products/60/thumbnail.jpg",
    ],
    stock: 129,
    review: [],
  },
  {
    title: "Women Strip Heel",
    description:
      "Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped",
    price: 40,
    discountPercentage: 10.83,
    rating: 4.02,
    brand: "Sandals Flip Flops",
    category: "womens-shoes",
    image: "https://i.dummyjson.com/data/products/48/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/48/1.jpg",
      "https://i.dummyjson.com/data/products/48/2.jpg",
      "https://i.dummyjson.com/data/products/48/3.jpg",
      "https://i.dummyjson.com/data/products/48/4.jpg",
      "https://i.dummyjson.com/data/products/48/thumbnail.jpg",
    ],
    stock: 25,
    review: [],
  },
  {
    title: "Rose Ring",
    description:
      "Brand: The Greetings Flower Colour: RedRing Colour: GoldenSize: Adjustable",
    price: 100,
    discountPercentage: 3.22,
    rating: 4.21,
    brand: "Copenhagen Luxe",
    category: "womens-jewellery",
    image: "https://i.dummyjson.com/data/products/77/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/77/1.jpg",
      "https://i.dummyjson.com/data/products/77/2.jpg",
      "https://i.dummyjson.com/data/products/77/3.jpg",
      "https://i.dummyjson.com/data/products/77/thumbnail.jpg",
    ],
    stock: 149,
    review: [],
  },
  {
    title: "Elegant Female Pearl Earrings",
    description:
      "Elegant Female Pearl Earrings Set Zircon Pearl Earings Women Party Accessories 9 Pairs/Set",
    price: 30,
    discountPercentage: 12.8,
    rating: 4.74,
    brand: "Fashion Jewellery",
    category: "womens-jewellery",
    image: "https://i.dummyjson.com/data/products/79/thumbnail.jpg",
    AdditionalImages: ["https://i.dummyjson.com/data/products/79/1.jpg"],
    stock: 16,
    review: [],
  },
  {
    title: "Chain Pin Tassel Earrings",
    description:
      "Pair Of Ear Cuff Butterfly Long Chain Pin Tassel Earrings - Silver ( Long Life Quality Product)",
    price: 45,
    discountPercentage: 17.75,
    rating: 4.59,
    brand: "Cuff Butterfly",
    category: "womens-jewellery",
    image: "https://i.dummyjson.com/data/products/80/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/80/1.jpg",
      "https://i.dummyjson.com/data/products/80/2.jpg",
      "https://i.dummyjson.com/data/products/80/3.png",
      "https://i.dummyjson.com/data/products/80/4.jpg",
      "https://i.dummyjson.com/data/products/80/thumbnail.jpg",
    ],
    stock: 9,
    review: [],
  },
  {
    title: "half sleeves T shirts",
    description:
      "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
    price: 23,
    discountPercentage: 12.76,
    rating: 3.2,
    brand: "Vintage Apparel",
    category: "mens-shirts",
    image: "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/51/1.png",
      "https://i.dummyjson.com/data/products/51/2.jpg",
      "https://i.dummyjson.com/data/products/51/3.jpg",
      "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
    ],
    stock: 132,
    review: [],
  },
  {
    title: "FREE FIRE T Shirt",
    description:
      "quality and professional print - It doesn't just look high quality, it is high quality.",
    price: 10,
    discountPercentage: 14.72,
    rating: 1.9,
    brand: "FREE FIRE",
    category: "mens-shirts",
    image: "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/52/1.png",
      "https://i.dummyjson.com/data/products/52/2.png",
      "https://i.dummyjson.com/data/products/52/3.jpg",
      "https://i.dummyjson.com/data/products/52/4.jpg",
      "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
    ],
    stock: 128,
    review: [],
  },
  {
    title: "printed high quality T shirts",
    description: "Brand: vintage Apparel ,Export quality",
    price: 35,
    discountPercentage: 7.54,
    rating: 4.89,
    brand: "Vintage Apparel",
    category: "mens-shirts",
    image: "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/53/1.webp",
      "https://i.dummyjson.com/data/products/53/2.jpg",
      "https://i.dummyjson.com/data/products/53/3.jpg",
      "https://i.dummyjson.com/data/products/53/4.jpg",
      "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
    ],
    stock: 6,
    review: [],
  },
  {
    title: "Pubg Printed Graphic T-Shirt",
    description:
      "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
    price: 46,
    discountPercentage: 16.44,
    rating: 4.62,
    brand: "The Warehouse",
    category: "mens-shirts",
    image: "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/54/1.jpg",
      "https://i.dummyjson.com/data/products/54/2.jpg",
      "https://i.dummyjson.com/data/products/54/3.jpg",
      "https://i.dummyjson.com/data/products/54/4.jpg",
      "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
    ],
    stock: 136,
    review: [],
  },
  {
    title: "Money Heist Printed Summer T Shirts",
    description: "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
    price: 66,
    discountPercentage: 15.97,
    rating: 4.9,
    brand: "The Warehouse",
    category: "mens-shirts",
    image: "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/55/1.jpg",
      "https://i.dummyjson.com/data/products/55/2.webp",
      "https://i.dummyjson.com/data/products/55/3.jpg",
      "https://i.dummyjson.com/data/products/55/4.jpg",
      "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
    ],
    stock: 122,
    review: [],
  },
  {
    title: "Round Silver Frame Sun Glasses",
    description:
      "A pair of sunglasses can protect your eyes from being hurt. For car driving, vacation travel, outdoor activities, social gatherings,",
    price: 19,
    discountPercentage: 10.1,
    rating: 4.94,
    brand: "Designer Sun Glasses",
    category: "sunglasses",
    image: "https://i.dummyjson.com/data/products/81/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/81/1.jpg",
      "https://i.dummyjson.com/data/products/81/2.jpg",
      "https://i.dummyjson.com/data/products/81/3.jpg",
      "https://i.dummyjson.com/data/products/81/4.webp",
      "https://i.dummyjson.com/data/products/81/thumbnail.jpg",
    ],
    stock: 78,
    review: [],
  },
  {
    title: "Kabir Singh Square Sunglass",
    description:
      "Orignal Metal Kabir Singh design 2020 Sunglasses Men Brand Designer Sun Glasses Kabir Singh Square Sunglass",
    price: 50,
    discountPercentage: 15.6,
    rating: 4.62,
    brand: "Designer Sun Glasses",
    category: "sunglasses",
    image: "https://i.dummyjson.com/data/products/82/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/82/1.jpg",
      "https://i.dummyjson.com/data/products/82/2.webp",
      "https://i.dummyjson.com/data/products/82/3.jpg",
      "https://i.dummyjson.com/data/products/82/4.jpg",
      "https://i.dummyjson.com/data/products/82/thumbnail.jpg",
    ],
    stock: 78,
    review: [],
  },
  {
    title: "Wiley X Night Vision Yellow Glasses",
    description:
      "Wiley X Night Vision Yellow Glasses for Riders - Night Vision Anti Fog Driving Glasses - Free Night Glass Cover - Shield Eyes From Dust and Virus- For Night Sport Matches",
    price: 30,
    discountPercentage: 6.33,
    rating: 4.97,
    brand: "mastar watch",
    category: "sunglasses",
    image: "https://i.dummyjson.com/data/products/83/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/83/1.jpg",
      "https://i.dummyjson.com/data/products/83/2.jpg",
      "https://i.dummyjson.com/data/products/83/3.jpg",
      "https://i.dummyjson.com/data/products/83/4.jpg",
      "https://i.dummyjson.com/data/products/83/thumbnail.jpg",
    ],
    stock: 115,
    review: [],
  },
  {
    title: "Square Sunglasses",
    description:
      "Fashion Oversized Square Sunglasses Retro Gradient Big Frame Sunglasses For Women One Piece Gafas Shade Mirror Clear Lens 17059",
    price: 28,
    discountPercentage: 13.89,
    rating: 4.64,
    brand: "mastar watch",
    category: "sunglasses",
    image: "https://i.dummyjson.com/data/products/84/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/84/1.jpg",
      "https://i.dummyjson.com/data/products/84/2.jpg",
      "https://i.dummyjson.com/data/products/84/thumbnail.jpg",
    ],
    stock: 64,
    review: [],
  },
  {
    title: "MacBook Pro",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    brand: "Apple",
    category: "laptops",
    image: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/6/1.png",
      "https://i.dummyjson.com/data/products/6/2.jpg",
      "https://i.dummyjson.com/data/products/6/3.png",
      "https://i.dummyjson.com/data/products/6/4.jpg",
    ],
    stock: 83,
    review: [],
  },
  {
    title: "LouisWill Men Sunglasses",
    description:
      "LouisWill Men Sunglasses Polarized Sunglasses UV400 Sunglasses Day Night Dual Use Safety Driving Night Vision Eyewear AL-MG Frame Sun Glasses with Free Box for Drivers",
    price: 50,
    discountPercentage: 11.27,
    rating: 4.98,
    brand: "LouisWill",
    category: "sunglasses",
    image: "https://i.dummyjson.com/data/products/85/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/85/1.jpg",
      "https://i.dummyjson.com/data/products/85/2.jpg",
      "https://i.dummyjson.com/data/products/85/thumbnail.jpg",
    ],
    stock: 92,
    review: [],
  },
  {
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    brand: "Samsung",
    category: "laptops",
    image: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/7/1.jpg",
      "https://i.dummyjson.com/data/products/7/2.jpg",
      "https://i.dummyjson.com/data/products/7/3.jpg",
      "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    ],
    stock: 50,
    review: [],
  },
  {
    title: "Microsoft Surface Laptop 4",
    description:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    price: 1499,
    discountPercentage: 10.23,
    rating: 4.43,
    brand: "Microsoft Surface",
    category: "laptops",
    image: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/8/1.jpg",
      "https://i.dummyjson.com/data/products/8/2.jpg",
      "https://i.dummyjson.com/data/products/8/3.jpg",
      "https://i.dummyjson.com/data/products/8/4.jpg",
      "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    ],
    stock: 68,
    review: [],
  },
  {
    title: "Infinix INBOOK",
    description:
      "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    price: 1099,
    discountPercentage: 11.83,
    rating: 4.54,
    brand: "Infinix",
    category: "laptops",
    image: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/9/1.jpg",
      "https://i.dummyjson.com/data/products/9/2.png",
      "https://i.dummyjson.com/data/products/9/3.png",
      "https://i.dummyjson.com/data/products/9/4.jpg",
      "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    ],
    stock: 96,
    review: [],
  },
  {
    title: "HP Pavilion 15-DK1056WM",
    description:
      "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    price: 1099,
    discountPercentage: 6.18,
    rating: 4.43,
    brand: "HP Pavilion",
    category: "laptops",
    image: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/10/1.jpg",
      "https://i.dummyjson.com/data/products/10/2.jpg",
      "https://i.dummyjson.com/data/products/10/3.jpg",
      "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    ],
    stock: 89,
    review: [],
  },
  {
    title: "perfume Oil",
    description:
      "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
    price: 13,
    discountPercentage: 8.4,
    rating: 2.5,
    brand: "Impression of Acqua Di Gio",
    category: "fragrances",
    image: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/11/1.jpg",
      "https://i.dummyjson.com/data/products/11/2.jpg",
      "https://i.dummyjson.com/data/products/11/3.jpg",
      "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    ],
    stock: 65,
    review: [],
  },
  {
    title: "Fog Scent Xpressio Perfume",
    description:
      "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    price: 13,
    discountPercentage: 8.14,
    rating: 4.59,
    brand: "Fog Scent Xpressio",
    category: "fragrances",
    image: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/13/1.jpg",
      "https://i.dummyjson.com/data/products/13/2.png",
      "https://i.dummyjson.com/data/products/13/3.jpg",
      "https://i.dummyjson.com/data/products/13/4.jpg",
      "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    ],
    stock: 61,
    review: [],
  },
  {
    title: "Brown Perfume",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    discountPercentage: 15.66,
    rating: 4,
    brand: "Royal_Mirage",
    category: "fragrances",
    image: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/12/1.jpg",
      "https://i.dummyjson.com/data/products/12/2.jpg",
      "https://i.dummyjson.com/data/products/12/3.png",
      "https://i.dummyjson.com/data/products/12/4.jpg",
      "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    ],
    stock: 52,
    review: [],
  },
  {
    title: "Non-Alcoholic Concentrated Perfume Oil",
    description:
      "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
    price: 120,
    discountPercentage: 15.6,
    rating: 4.21,
    brand: "Al Munakh",
    category: "fragrances",
    image: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/14/1.jpg",
      "https://i.dummyjson.com/data/products/14/2.jpg",
      "https://i.dummyjson.com/data/products/14/3.jpg",
      "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    ],
    stock: 114,
    review: [],
  },
  {
    title: "formal offices shoes",
    description:
      "Pattern Type: Solid, Material: PU, Toe Shape: Pointed Toe ,Outsole Material: Rubber",
    price: 57,
    discountPercentage: 12,
    rating: 2.5,
    brand: "The Warehouse",
    category: "mens-shoes",
    image: "https://i.dummyjson.com/data/products/58/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/58/1.jpg",
      "https://i.dummyjson.com/data/products/58/2.jpg",
      "https://i.dummyjson.com/data/products/58/3.jpg",
      "https://i.dummyjson.com/data/products/58/4.jpg",
      "https://i.dummyjson.com/data/products/58/thumbnail.jpg",
    ],
    stock: 68,
    review: [],
  },
  {
    title: "Leather Straps Wristwatch",
    description: "Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar",
    price: 120,
    discountPercentage: 7.14,
    rating: 4.63,
    brand: "Naviforce",
    category: "mens-watches",
    image: "https://i.dummyjson.com/data/products/61/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/61/1.jpg",
      "https://i.dummyjson.com/data/products/61/2.png",
      "https://i.dummyjson.com/data/products/61/3.jpg",
    ],
    stock: 91,
    review: [],
  },
  {
    title: "Waterproof Leather Brand Watch",
    description:
      "Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours",
    price: 46,
    discountPercentage: 3.15,
    rating: 4.05,
    brand: "SKMEI 9117",
    category: "mens-watches",
    image: "https://i.dummyjson.com/data/products/62/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/62/1.jpg",
      "https://i.dummyjson.com/data/products/62/2.jpg",
    ],
    stock: 95,
    review: [],
  },
  {
    title: "Rhinestone Korean Style Open Rings",
    description:
      "Fashion Jewellery 3Pcs Adjustable Pearl Rhinestone Korean Style Open Rings For Women",
    price: 30,
    discountPercentage: 8.02,
    rating: 4.69,
    brand: "Fashion Jewellery",
    category: "womens-jewellery",
    image: "https://i.dummyjson.com/data/products/78/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/78/thumbnail.jpg",
    ],
    stock: 9,
    review: [],
  },
  {
    title: "Leather Strap Skeleton Watch",
    description:
      "Leather Strap Skeleton Watch for Men - Stylish and Latest Design",
    price: 46,
    discountPercentage: 10.2,
    rating: 4.98,
    brand: "Strap Skeleton",
    category: "mens-watches",
    image: "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/64/1.jpg",
      "https://i.dummyjson.com/data/products/64/2.webp",
      "https://i.dummyjson.com/data/products/64/3.jpg",
      "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
    ],
    stock: 61,
    review: [],
  },
  {
    title: "Stainless Steel Wrist Watch",
    description:
      "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
    price: 47,
    discountPercentage: 17.79,
    rating: 4.79,
    brand: "Stainless",
    category: "mens-watches",
    image: "https://i.dummyjson.com/data/products/65/thumbnail.webp",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/65/1.jpg",
      "https://i.dummyjson.com/data/products/65/2.webp",
      "https://i.dummyjson.com/data/products/65/3.jpg",
      "https://i.dummyjson.com/data/products/65/4.webp",
      "https://i.dummyjson.com/data/products/65/thumbnail.webp",
    ],
    stock: 94,
    review: [],
  },
  {
    title: "Eau De Perfume Spray",
    description:
      "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    price: 30,
    discountPercentage: 10.99,
    rating: 4.7,
    brand: "Lord - Al-Rehab",
    category: "fragrances",
    image: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/15/1.jpg",
      "https://i.dummyjson.com/data/products/15/2.jpg",
      "https://i.dummyjson.com/data/products/15/3.jpg",
      "https://i.dummyjson.com/data/products/15/4.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
    stock: 105,
    review: [],
  },
  {
    title: "Royal Blue Premium Watch",
    description:
      "Men Silver Chain Royal Blue Premium Watch Latest Analog Watch",
    price: 50,
    discountPercentage: 2.56,
    rating: 4.89,
    brand: "SKMEI 9117",
    category: "mens-watches",
    image: "https://i.dummyjson.com/data/products/63/thumbnail.webp",
    AdditionalImages: [
      "https://i.dummyjson.com/data/products/63/1.jpg",
      "https://i.dummyjson.com/data/products/63/2.jpg",
      "https://i.dummyjson.com/data/products/63/3.png",
      "https://i.dummyjson.com/data/products/63/4.jpeg",
    ],
    stock: 142,
    review: [],
  },
];

module.exports = { products };
